---
title: "socialNavigationAnalysis"
author: "Neel"
date: "2026-05-24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("C:/Users/mcpro/OneDrive/Documents/WAVE LAB/Code/socialNavigation/tools")

library(tidyverse)
library(paletteer)
library(afex)
library(emmeans)
library(purrr)
library(jsonlite)
```

```{r}
all_data <- read.csv("data/dataframe_answer.csv", header=TRUE)
debrief_data <- read.csv("data/dataframe_debrief.csv", header=TRUE)

#delete all test data

all_data <- all_data |>
  filter(participant_id != "{{%PROLIFIC_PID%}}") |>
  filter(!str_detect(participant_id, "no_query_worker"))

debrief_data <- debrief_data |>
  filter(participant_id != "{{%PROLIFIC_PID%}}") |>
  filter(!str_detect(participant_id, "no_query_worker")) 
 
uniq <- unique(all_data$participant_id)
uniq

length(uniq)
```
```{r}
to_remove_debrief_by_id <- debrief_data |>
  group_by(participant_id) |>
  mutate(response_parsed = map(response, fromJSON)) |>
  hoist(response_parsed, attention = "attention") |>
  mutate(attention = as.numeric(attention)) |>
  filter(attention < 85)

to_remove <- to_remove_debrief_by_id$participant_id

all_data_clean <- all_data |>
  filter(!participant_id %in% to_remove)

cat("Participants removed:", nrow(to_remove_debrief_by_id))
```



```{r}
shorter_data <- all_data_clean |>
  select(participant_id, trial_number, response, response_time, accuracy, trial_rotation, trial_reflection, stripe_angle_top, stripe_angle_bottom, background_group, identical)

grouped_by_pid <- shorter_data |>
  group_by(participant_id) |>
  summarize(num_trials = n(),
            meanRT = mean(response_time),
            sdRT = sd(response_time))
  
grand_meanRT <- mean(grouped_by_pid$meanRT)
grand_sdRT <- sd(grouped_by_pid$meanRT)

sd_threshold <- 2.0

upper_bound <- grand_meanRT + sd_threshold * grand_sdRT
lower_bound <- grand_meanRT - sd_threshold * grand_sdRT

grouped_by_pid <- grouped_by_pid |>
  filter(num_trials > 45) |> ## change num as needed
  filter(meanRT < upper_bound & meanRT > lower_bound)


good_participants <- grouped_by_pid$participant_id
```


```{r}
good_clean_data <- shorter_data |>
  filter(participant_id %in% good_participants)

individual_trial_sd_threshold <- 2.5

fused_ind_exclude <- left_join(good_clean_data, grouped_by_pid,
              by = "participant_id") |>
  filter(response_time > meanRT - individual_trial_sd_threshold * sdRT & response_time < meanRT + individual_trial_sd_threshold * sdRT)

fused_ind_exclude$trial_rotation = as.factor(fused_ind_exclude$trial_rotation)
fused_ind_exclude$trial_reflection = as.factor(fused_ind_exclude$trial_reflection)

cat("Valid Participants:", nrow(grouped_by_pid))
```




```{r}
rt_by_group <- fused_ind_exclude |> 
  filter(accuracy == 1) |>
  group_by(background_group) |>
  summarize(
    mean = mean(meanRT),
    sd = sd(meanRT),
    n = n(),
    se = sd/sqrt(n)
  )

ggplot(rt_by_group, aes(x=background_group, y=mean, fill=background_group)) +
  geom_col() + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se)) +
  labs(title= "Task Reaction Time by Background Group, Filtered", x="Conditon", y="Reaction Time, ms") +
  scale_fill_paletteer_d("MetBrewer::Austria")



```


```{r}
grouped_data_RT <- fused_ind_exclude |>
  filter(accuracy == 1) |>
  group_by(participant_id, background_group) |>
  summarize(meanRT = mean(response_time)) |>
  ungroup()


RT_anova <- aov_ez(id = "participant_id",
                   dv = "meanRT",
                   data = grouped_data_RT,
                   within = "background_group")

summary(RT_anova)

emmeans(RT_anova, pairwise ~ background_group, adjust = "tukey")



```


```{r}

accuracy_data <- fused_ind_exclude |>
  group_by(background_group) |>
  summarize(
    mean = mean(accuracy),
    sd = sd(accuracy),
    n = n(),
    se = sd/sqrt(n)
  )

ggplot(accuracy_data, aes(x=background_group, y=mean, fill=background_group)) +
  geom_col() +
  geom_errorbar(aes(ymin= mean - se, ymax = mean + se)) +
  labs(title = "Stripe Angle Match Accuracy by Background Group", x="Condition", y= "Accuracy") + 
  scale_fill_paletteer_d("MoMAColors::Budnitz")


grouped_data_Acc <- fused_ind_exclude |>
  group_by(participant_id, background_group) |>
  summarize(meanAcc = mean(accuracy)) |>
  ungroup()


acc_anova <- aov_ez(id = "participant_id",
                   dv = "meanAcc",
                   data = grouped_data_Acc,
                   within = "background_group")

summary(acc_anova)

emmeans(acc_anova, pairwise ~ background_group, adjust = "tukey")


```

```{r}

rt_by_rotation <- fused_ind_exclude |> 
  filter(accuracy == 1) |>
  group_by(trial_rotation) |>
  summarize(
    mean = mean(response_time),
    sd = sd(response_time),
    n = n(),
    se = sd/sqrt(n)
  )

ggplot(rt_by_rotation, aes(x=trial_rotation, y=mean, fill=trial_rotation)) +
  geom_col() + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se)) +
  labs(title= "Task Reaction Time by Rotation, Filtered", x="Rotation, Degrees", y="Reaction Time, ms")


rt_by_reflection <- fused_ind_exclude |> 
  filter(accuracy == 1) |>
  group_by(trial_reflection) |>
  summarize(
    mean = mean(response_time),
    sd = sd(response_time),
    n = n(),
    se = sd/sqrt(n)
  )

ggplot(rt_by_reflection, aes(x=trial_reflection, y=mean, fill=trial_reflection)) +
  geom_col() + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se)) +
  labs(title= "Task Reaction Time by Reflection", x="Reflection", y="Reaction Time, ms")



```

```{r}
#anova on rt by rotation: 

grouped_data_RT <- fused_ind_exclude |>
  filter(accuracy == 1) |>
  group_by(participant_id, trial_rotation) |>
  summarize(meanRT = mean(response_time)) |>
  ungroup()

grouped_data_RT$trial_rotation = as.factor(grouped_data_RT$trial_rotation)


RT_anova <- aov_ez(id = "participant_id",
                   dv = "meanRT",
                   data = grouped_data_RT,
                   within = "trial_rotation")

summary(RT_anova)

emmeans(RT_anova, pairwise ~ trial_rotation, adjust = "tukey")


```


```{r}
accuracy_by_rotation <- fused_ind_exclude |> 
  group_by(trial_rotation) |>
  summarize(
    mean = mean(accuracy),
    sd = sd(accuracy),
    n = n(),
    se = sd/sqrt(n)
  )

ggplot(accuracy_by_rotation, aes(x=trial_rotation, y=mean, fill=trial_rotation)) +
  geom_col() + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se)) +
  labs(title= "Stripe Angle Match Accuracy by Rotation, Filitered", x="Rotation, Degrees", y="Accuracy")


accuracy_by_reflection <- fused_ind_exclude |> 
  group_by(trial_reflection) |>
  summarize(
    mean = mean(accuracy),
    sd = sd(accuracy),
    n = n(),
    se = sd/sqrt(n)
  )

ggplot(accuracy_by_reflection, aes(x=trial_reflection, y=mean, fill=trial_reflection)) +
  geom_col() + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se)) +
  labs(title= "Stripe Angle Match Accuracy by Reflection", x="Reflection", y="Accuracy")



```

```{r}
#what does the anova look like (for trial rotation)?
grouped_data_accuracy <- fused_ind_exclude |>
  group_by(participant_id, trial_rotation) |>
  summarize(mean_acc = mean(accuracy)) |>
  ungroup()


grouped_data_accuracy$trial_rotation = as.factor(grouped_data_accuracy$trial_rotation)

accuracy_anova <- aov_ez(id = "participant_id",
                   dv = "mean_acc",
                   data = grouped_data_accuracy,
                   within = "trial_rotation")

summary(accuracy_anova)

emmeans(accuracy_anova, pairwise ~ trial_rotation, adjust = "tukey")


```
```{r}
#what about reflection?
grouped_data_accuracy <- fused_ind_exclude |>
  group_by(participant_id, trial_reflection) |>
  summarize(mean_acc = mean(accuracy)) |>
  ungroup()


grouped_data_accuracy$trial_reflection = as.factor(grouped_data_accuracy$trial_reflection)

accuracy_anova <- aov_ez(id = "participant_id",
                   dv = "mean_acc",
                   data = grouped_data_accuracy,
                   within = "trial_reflection")

summary(accuracy_anova)

emmeans(accuracy_anova, pairwise ~ trial_reflection, adjust = "tukey")


```



```{r}
#next: first half second half, all group conditions for each disp_time, trials after attention checks, rotations, reflections?

firstHalf_data <- fused_ind_exclude |>
  arrange(participant_id, trial_number) |>
  group_by(participant_id) |>
  slice_head(prop = 0.5) |>
  ungroup()

secondHalf_data <- fused_ind_exclude |>
  arrange(participant_id, trial_number) |>
  group_by(participant_id) |>
  slice_tail(prop = 0.5) |>
  ungroup()



```

```{r}
rt_by_group <- firstHalf_data |> 
  filter(accuracy == 1) |>
  group_by(background_group) |>
  summarize(
    mean = mean(response_time),
    sd = sd(response_time),
    n = n(),
    se = sd/sqrt(n)
  )

ggplot(rt_by_group, aes(x=background_group, y=mean, fill=background_group)) +
  geom_col() + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se)) +
  labs(title= "Task Reaction Time by Background Group, First Half", x="Conditon", y="Reaction Time, ms") +
  scale_fill_paletteer_d("MetBrewer::Austria")


```

```{r}
grouped_data_RT <- firstHalf_data |>
  filter(accuracy == 1) |>
  group_by(participant_id, background_group) |>
  summarize(meanRT = mean(response_time)) |>
  ungroup()

grouped_data_RT$background_group = as.factor(grouped_data_RT$background_group)
  
  
RT_anova <- aov_ez(id = "participant_id",
                   dv = "meanRT",
                   data = grouped_data_RT,
                   within = "background_group")

summary(RT_anova)

emmeans(RT_anova, pairwise ~ background_group, adjust = "tukey")
```

```{r} 
rt_by_group <- secondHalf_data |> 
  filter(accuracy == 1) |>
  group_by(background_group) |>
  summarize(
    mean = mean(response_time),
    sd = sd(response_time),
    n = n(),
    se = sd/sqrt(n)
  )

ggplot(rt_by_group, aes(x=background_group, y=mean, fill=background_group)) +
  geom_col() + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se)) +
  labs(title= "Task Reaction Time by Background Group, Second Half", x="Conditon", y="Reaction Time, ms") +
  scale_fill_paletteer_d("MetBrewer::Austria")

```


```{r}

grouped_data_RT <- secondHalf_data |>
  filter(accuracy == 1) |>
  group_by(participant_id, background_group) |>
  summarize(meanRT = mean(response_time)) |>
  ungroup()

grouped_data_RT$background_group = as.factor(grouped_data_RT$background_group)
  
  
RT_anova <- aov_ez(id = "participant_id",
                   dv = "meanRT",
                   data = grouped_data_RT,
                   within = "background_group")

summary(RT_anova)

emmeans(RT_anova, pairwise ~ background_group, adjust = "tukey")
```


```{r}

accuracy_data <- firstHalf_data |>
  group_by(background_group) |>
  summarize(
    mean = mean(accuracy),
    sd = sd(accuracy),
    n = n(),
    se = sd/sqrt(n)
  )

ggplot(accuracy_data, aes(x=background_group, y=mean, fill=background_group)) +
  geom_col() +
  geom_errorbar(aes(ymin= mean - se, ymax = mean + se)) +
  labs(title = "Stripe Angle Match Accuracy by Background Group, First Half", x="Condition", y= "Accuracy") + 
  scale_fill_paletteer_d("MoMAColors::Budnitz")


grouped_data_accuracy <- firstHalf_data |>
  group_by(participant_id, background_group) |>
  summarize(mean_acc = mean(accuracy)) |>
  ungroup()


grouped_data_accuracy$background_group = as.factor(grouped_data_accuracy$background_group)

accuracy_anova <- aov_ez(id = "participant_id", 
                   dv = "mean_acc", 
                   data = grouped_data_accuracy, 
                   within = "background_group")

summary(accuracy_anova)

emmeans(accuracy_anova, pairwise ~ background_group, adjust = "tukey")


```

```{r}

accuracy_data <- secondHalf_data |>
  group_by(background_group) |>
  summarize(
    mean = mean(accuracy),
    sd = sd(accuracy),
    n = n(),
    se = sd/sqrt(n)
  )

ggplot(accuracy_data, aes(x=background_group, y=mean, fill=background_group)) +
  geom_col() +
  geom_errorbar(aes(ymin= mean - se, ymax = mean + se)) +
  labs(title = "Stripe Angle Match Accuracy by Background Group, Second Half", x="Condition", y= "Accuracy") + 
  scale_fill_paletteer_d("MoMAColors::Budnitz")


grouped_data_accuracy <- secondHalf_data |>
  group_by(participant_id, background_group) |>
  summarize(mean_acc = mean(accuracy)) |>
  ungroup()


grouped_data_accuracy$background_group = as.factor(grouped_data_accuracy$background_group)

accuracy_anova <- aov_ez(id = "participant_id", 
                   dv = "mean_acc", 
                   data = grouped_data_accuracy, 
                   within = "background_group")

summary(accuracy_anova)

emmeans(accuracy_anova, pairwise ~ background_group, adjust = "tukey")

```

```{r}
#TIME FOR FAST AND SLOW RESPONDERS

speeds <- fused_ind_exclude |>
  group_by(participant_id) |>
  summarize(meanRT = mean(response_time)) |>
  mutate(
    response_speed = ifelse(meanRT <= mean(meanRT), "fast", "slow"
    )
  ) 
  
fused_ind_exclude <- fused_ind_exclude |>
  left_join(speeds, by = "participant_id")

fused_ind_exclude |>
  count(response_speed)

```

```{r}
rt_by_group <- fused_ind_exclude |> 
  filter(accuracy == 1, response_speed == "fast") |> 
  group_by(background_group) |>
  summarize(
    mean = mean(response_time),
    sd = sd(response_time),
    n = n(),
    se = sd/sqrt(n)
  )

ggplot(rt_by_group, aes(x=background_group, y=mean, fill=background_group)) +
  geom_col() + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se)) +
  labs(title= "Task Reaction Time by Background Group, Fast Responders", x="Conditon", y="Reaction Time, ms") +
  scale_fill_paletteer_d("MetBrewer::Austria")



grouped_data_RT <- fused_ind_exclude |>
  filter(response_speed == "fast", accuracy == 1) |>
  group_by(participant_id, background_group) |>
  summarize(meanRT = mean(response_time)) |>
  ungroup()

grouped_data_RT$background_group = as.factor(grouped_data_RT$background_group)
  
  
RT_anova <- aov_ez(id = "participant_id",
                   dv = "meanRT",
                   data = grouped_data_RT,
                   within = "background_group")

summary(RT_anova)

emmeans(RT_anova, pairwise ~ background_group, adjust = "tukey")

```
```{r}
accuracy_data <- fused_ind_exclude |>
  filter(response_speed == "fast") |>
  group_by(background_group) |>
  summarize(
    mean = mean(accuracy),
    sd = sd(accuracy),
    n = n(),
    se = sd/sqrt(n)
  )

ggplot(accuracy_data, aes(x=background_group, y=mean, fill=background_group)) +
  geom_col() +
  geom_errorbar(aes(ymin= mean - se, ymax = mean + se)) +
  labs(title = "Stripe Angle Match Accuracy by Background Group, Fast Responders", x="Condition", y= "Accuracy") + 
  scale_fill_paletteer_d("MoMAColors::Budnitz")

grouped_data_accuracy <- fused_ind_exclude |>
  filter(response_speed == "fast") |>
  group_by(participant_id, background_group) |>
  summarize(mean_acc = mean(accuracy)) |>
  ungroup()


grouped_data_accuracy$background_group = as.factor(grouped_data_accuracy$background_group)

accuracy_anova <- aov_ez(id = "participant_id", 
                   dv = "mean_acc", 
                   data = grouped_data_accuracy, 
                   within = "background_group")

summary(accuracy_anova)

emmeans(accuracy_anova, pairwise ~ background_group, adjust = "tukey")

```

```{r}
firstHalf_data_fast <- fused_ind_exclude |>
  filter(response_speed == "fast") |>
  arrange(participant_id, trial_number) |>
  group_by(participant_id) |>
  slice_head(prop = 0.5) |>
  ungroup()

secondHalf_data_fast <- fused_ind_exclude |>
  filter(response_speed == "fast") |>
  arrange(participant_id, trial_number) |>
  group_by(participant_id) |>
  slice_tail(prop = 0.5) |>
  ungroup()


```



```{r}

rt_by_group <- firstHalf_data_fast |> 
  filter(accuracy == 1) |>
  group_by(background_group) |>
  summarize(
    mean = mean(response_time),
    sd = sd(response_time),
    n = n(),
    se = sd/sqrt(n)
  )

ggplot(rt_by_group, aes(x=background_group, y=mean, fill=background_group)) +
  geom_col() + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se)) +
  labs(title= "Task Reaction Time by Background Group, First Half, Fast Responders", x="Conditon", y="Reaction Time, ms") +
  scale_fill_paletteer_d("MetBrewer::Austria")

grouped_data_RT <- firstHalf_data_fast |>
  filter(accuracy == 1) |>
  group_by(participant_id, background_group) |>
  summarize(meanRT = mean(response_time)) |>
  ungroup()

grouped_data_RT$background_group = as.factor(grouped_data_RT$background_group)
  
  
RT_anova <- aov_ez(id = "participant_id",
                   dv = "meanRT",
                   data = grouped_data_RT,
                   within = "background_group")

summary(RT_anova)

emmeans(RT_anova, pairiwse ~ background_group, adjust = "tukey")

```


```{r}

rt_by_group <- secondHalf_data_fast |> 
  filter(accuracy == 1) |>
  group_by(background_group) |>
  summarize(
    mean = mean(response_time),
    sd = sd(response_time),
    n = n(),
    se = sd/sqrt(n)
  )

ggplot(rt_by_group, aes(x=background_group, y=mean, fill=background_group)) +
  geom_col() + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se)) +
  labs(title= "Task Reaction Time by Background Group, Second Half, Fast Responders", x="Conditon", y="Reaction Time, ms") +
  scale_fill_paletteer_d("MetBrewer::Austria")

grouped_data_RT <- secondHalf_data_fast |>
  filter(accuracy == 1) |>
  group_by(participant_id, background_group) |>
  summarize(meanRT = mean(response_time)) |>
  ungroup()

grouped_data_RT$background_group = as.factor(grouped_data_RT$background_group)
  
  
RT_anova <- aov_ez(id = "participant_id",
                   dv = "meanRT",
                   data = grouped_data_RT,
                   within = "background_group")

summary(RT_anova)

emmeans(RT_anova, pairwise ~ background_group, adjust = "tukey")

```


```{r}
accuracy_data <- firstHalf_data_fast |>
  group_by(background_group) |>
  summarize(
    mean = mean(accuracy),
    sd = sd(accuracy),
    n = n(),
    se = sd/sqrt(n)
  )

ggplot(accuracy_data, aes(x=background_group, y=mean, fill=background_group)) +
  geom_col() +
  geom_errorbar(aes(ymin= mean - se, ymax = mean + se)) +
  labs(title = "Stripe Angle Match Accuracy by Background Group, First Half, Fast Responders", x="Condition", y= "Accuracy") + 
  scale_fill_paletteer_d("MoMAColors::Budnitz")


grouped_data_accuracy <- firstHalf_data_fast |>
  group_by(participant_id, background_group) |>
  summarize(mean_acc = mean(accuracy)) |>
  ungroup()


grouped_data_accuracy$background_group = as.factor(grouped_data_accuracy$background_group)

accuracy_anova <- aov_ez(id = "participant_id", 
                   dv = "mean_acc", 
                   data = grouped_data_accuracy, 
                   within = "background_group")

summary(accuracy_anova)

emmeans(accuracy_anova, pairwise ~ background_group, adjust = "tukey")

```


```{r}
accuracy_data <- secondHalf_data_fast |>
  group_by(background_group) |>
  summarize(
    mean = mean(accuracy),
    sd = sd(accuracy),
    n = n(),
    se = sd/sqrt(n)
  )

ggplot(accuracy_data, aes(x=background_group, y=mean, fill=background_group)) +
  geom_col() +
  geom_errorbar(aes(ymin= mean - se, ymax = mean + se)) +
  labs(title = "Stripe Angle Match Accuracy by Background Group, Second Half, Fast Responders", x="Condition", y= "Accuracy") + 
  scale_fill_paletteer_d("MoMAColors::Budnitz")


grouped_data_accuracy <- secondHalf_data_fast |>
  group_by(participant_id, background_group) |>
  summarize(mean_acc = mean(accuracy)) |>
  ungroup()


grouped_data_accuracy$background_group = as.factor(grouped_data_accuracy$background_group)

accuracy_anova <- aov_ez(id = "participant_id", 
                   dv = "mean_acc", 
                   data = grouped_data_accuracy, 
                   within = "background_group")

summary(accuracy_anova)


emmeans(accuracy_anova, pairwise ~ background_group, adjust = "tukey")

```


```{r}
#RT by group fixed for 90 degrees
rt_by_group <- fused_ind_exclude |> 
  filter(accuracy == 1, trial_rotation == 90) |>
  group_by(background_group) |>
  summarize(
    mean = mean(response_time),
    sd = sd(response_time),
    n = n(),
    se = sd/sqrt(n)
  )

ggplot(rt_by_group, aes(x=background_group, y=mean, fill=background_group)) +
  geom_col() + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se)) +
  labs(title= "Task Reaction Time by Background Group, Filtered at 2.5SD, 90 Degree Trials", x="Conditon", y="Reaction Time, ms") +
  scale_fill_paletteer_d("MetBrewer::Austria")

grouped_data_RT <- fused_ind_exclude |>
  filter(trial_rotation == 90, accuracy == 1) |>
  group_by(participant_id, background_group) |>
  summarize(meanRT = mean(response_time)) |>
  ungroup()

grouped_data_RT$background_group = as.factor(grouped_data_RT$background_group)
  
  
RT_anova <- aov_ez(id = "participant_id",
                   dv = "meanRT",
                   data = grouped_data_RT,
                   within = "background_group")

summary(RT_anova)

emmeans(RT_anova, pairiwse ~ background_group, adjust = "tukey")

```


```{r}

m180_data <- fused_ind_exclude |>
  filter(trial_rotation == 180, trial_reflection == -1)

p0_data <- fused_ind_exclude |>
  filter(trial_rotation == 0, trial_reflection == 1)

m180_p0_data <- bind_rows(m180_data, p0_data)

rt_by_group <- m180_p0_data |> 
  filter(accuracy == 1) |>
  group_by(background_group) |>
  summarize(
    mean = mean(response_time),
    sd = sd(response_time),
    n = n(),
    se = sd/sqrt(n)
  )

ggplot(rt_by_group, aes(x=background_group, y=mean, fill=background_group)) +
  geom_col() + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se)) +
  labs(title= "Task Reaction Time by Background Group, Pooled 180Deg x -1 & 0Deg x 1", x="Conditon", y="Reaction Time, ms") +
  scale_fill_paletteer_d("MetBrewer::Austria")

grouped_data_RT <- m180_p0_data |>
  group_by(participant_id, background_group) |>
  summarize(meanRT = mean(response_time)) |>
  ungroup()

grouped_data_RT$background_group = as.factor(grouped_data_RT$background_group)
  
  
RT_anova <- aov_ez(id = "participant_id",
                   dv = "meanRT",
                   data = grouped_data_RT,
                   within = "background_group")

summary(RT_anova)

RT_hoc <- emmeans(RT_anova, ~background_group)

pairs(RT_hoc, adjust = "tukey")
```

```{r}

p180_data <- fused_ind_exclude |>
  filter(trial_rotation == 180, trial_reflection == 1)

m0_data <- fused_ind_exclude |>
  filter(trial_rotation == 0, trial_reflection == -1)

p180_m0_data <- bind_rows(p180_data, m0_data)

rt_by_group <- p180_m0_data |> 
  filter(accuracy == 1) |>
  group_by(background_group) |>
  summarize(
    mean = mean(response_time),
    sd = sd(response_time),
    n = n(),
    se = sd/sqrt(n)
  )

ggplot(rt_by_group, aes(x=background_group, y=mean, fill=background_group)) +
  geom_col() + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se)) +
  labs(title= "Task Reaction Time by Background Group, Pooled 180Deg x 1 & 0Deg x -1", x="Conditon", y="Reaction Time, ms") +
  scale_fill_paletteer_d("MetBrewer::Austria")

grouped_data_RT <- p180_m0_data |>
  filter(accuracy == 1) |>
  group_by(participant_id, background_group) |>
  summarize(meanRT = mean(response_time)) |>
  ungroup()

grouped_data_RT$background_group = as.factor(grouped_data_RT$background_group)
  
  
RT_anova <- aov_ez(id = "participant_id",
                   dv = "meanRT",
                   data = grouped_data_RT,
                   within = "background_group")
#test_anova <- aov(meanRT ~ background_group, data=grouped_data_RT)
#summary(test_anova)

summary(RT_anova)

RT_hoc <- emmeans(RT_anova, ~background_group)

pairs(RT_hoc, adjust = "tukey")
```

